# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Check out sources'
        uses: actions/checkout@v2
      - name: 'Set up JDK'
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: 'Cache local Maven repository'
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: 'Build'
        run: mvn --batch-mode --no-transfer-progress verify
      - name: 'Run integration tests'
        run: mvn --batch-mode --no-transfer-progress -Prun-its verify
      - name: 'Upload IT build logs as ${{ github.event.repository.name }}-build-${{ github.sha }}'
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-build-${{ github.sha }}
          path: |
            LICENSE
            target/it/*/build.log
