# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [21]

    steps:
      - name: 'Check out sources'
        uses: actions/checkout@v4
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: ${{ matrix.java }}
      - name: 'Build'
        run: mvn --batch-mode --no-transfer-progress verify
      - name: 'Run integration tests'
        run: mvn --batch-mode --no-transfer-progress -Prun-its verify
      - name: 'Upload IT build logs as ${{ github.event.repository.name }}-build-${{ github.sha }}'
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-build-${{ github.sha }}
          path: |
            LICENSE
            target/it/*/build.log
