name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out sources'
        uses: actions/checkout@v3
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 18
      - name: 'Build and Sign'
        run: mvn --batch-mode --no-transfer-progress -Prun-sign verify
